use_frameworks!

platform :ios, '8.0'

target 'YRKDataAnalyzer_Example' do
  pod 'YRKDataAnalyzer', :path => '../'

  target 'YRKDataAnalyzer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
